[project]
name = "subtitle-process"
version = "0.9.6"
description = "基于 Python 和 CustomTkinter 开发的本地字幕处理工具箱"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
dependencies = [
    "customtkinter",
    "tkinterdnd2",
]

[dependency-groups]
dev = [
    "pyinstaller",
]

[tool.uv]
package = false
